### ISSUE TITLE
rule

### ISSUE THREAD

**Issue by beyondmars3** [StarPlatinumStudio/FlinkAlarmOpsSys#1]
你这个rule表，规则好简单。一般的情况有： 出现一个关键字, 在一定时间内，超过一定次数，才发送告警。 比如error日志1分钟大于10次告警。这种怎么办呢？ flink 的 timeWindow时间是 死的呀，有100条这样的规则，就不好弄了。

**Comment by StarPlatinumStudio** [comment]
你好，这个项目现在已经完善并且在线上运行，在github上的源码还有很多不足之处，我最终的逻辑是这样的：
以一分钟的时间窗口聚合为WordWithCount的流再以一秒钟的时间窗口聚合为一条json发送到后端API
DataStream<WordWithCount&gt; windowCounts = stream
        .map(keyWord -&gt; {return new WordWithCount(keyWord,1);})
        .keyBy(WordWithCount::getWord)
        .timeWindow(Time.minutes(1))
        .sum("count");
windowCounts
        .windowAll(TumblingProcessingTimeWindows.of(Time.seconds(1)))
        .process(new collectProcessFuntion(config.getJobId()))
        .addSink(new HttpSink(config.getApiURL()));我在后端定义了一个长度为60的队列就是一小时（也可以更大），将每分钟的数据记录上去并且计算是否符合报警规则，这样数据不落地就可以在内存内直接计算任意分钟的规则。
&nbsp; 我后来看大神zhisheng的运维告警系统计算结果是直接在flink里计算出报警结果并计入数据库落地的https://www.bilibili.com/video/av80497878/





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"beyondmars3"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 上午9:52
收件人:&nbsp;"StarPlatinumStudio/FlinkAlarmOpsSys"<FlinkAlarmOpsSys@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[StarPlatinumStudio/FlinkAlarmOpsSys] rule (#1)




你这个rule表，规则好简单。一般的情况有： 出现一个关键字, 在一定时间内，超过一定次数，才发送告警。 比如error日志1分钟大于10次告警。这种怎么办呢？ flink 的 timeWindow时间是 死的呀，有100条这样的规则，就不好弄了。
